### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by JLEGit** [EmperorCookie/accapi#17]
![image](https://user-images.githubusercontent.com/55048956/107503068-cbe6c900-6b99-11eb-8866-90c428993619.png)

Hello, I would like to launch your "accapi" project but here is the error message I get with setup.py.

Can you help me? Thank you very much.

**Comment by EmperorCookie** [comment]
Hi, `setup.py` is usually used by `pip` internally. You would want to clone the repository, navigate to where you cloned it and then run `pip install -U -e .`. Make sure you're using Python 3.7+.

**Comment by JLEGit** [comment]
Hi, i use Python 3.9, it's good ?

**Comment by JLEGit** [comment]
So to launch the application, I just need to do pip install -U -e   ?

**Comment by EmperorCookie** [comment]
Oh I understand the confusion, this is not an application (yet) it's a library that a developer would use to create an application.
