### ISSUE TITLE
Possible example of connecting to the broadcast server

### ISSUE THREAD

**Issue by MMsicarius** [EmperorCookie/accapi#21]
Hello there

Is there any chance of including a simple example of using your api wrapper to connect to broadcast server? There isn't any documentation on how to use api wrapper and there isn't many hints in the comments within the code. Could you add a simple example that outputs some data to demonstrate how to use and apply the wrapper.

Thanks

**Comment by BruceEus** [comment]
Hey, i'm trying to get connected to the ACC Broadcast stream as well.
Did you ever manager to get it working ? I can't get this code to work.

Thanks !

**Comment by EmperorCookie** [comment]
Hey there, I managed to find some time to add an example in the [README](https://github.com/EmperorCookie/accapi/blob/main/README.md).

Note that this hasn't been updated in a long time, so if Kunoz modified the interface a bunch of stuff might be broken.

If this is still the only Python package that can talk to ACC, feel free to open an issue for the broken features and I'll do my best to find some time to fix them.
