### ISSUE TITLE
How to add other realtime car data?

### ISSUE THREAD

**Issue by chane1005** [EmperorCookie/accapi#22]
as title, sorry for disturb but I want to check other realtime car data like steering angle, throttle and brake etc, how can I do it?

**Comment by EmperorCookie** [comment]
When I made this tool, I made sure to include all information that was available. Unfortunately, that means you'd need to get this information elsewhere. I know the replay saves that information so maybe a replay analyser tool could have that kind of information?

Disclaimer, I did a cursory search and didn't find any information about Kunos adding more data channels to this system, but I didn't dig very deep.

**Comment by chane1005** [comment]
Thank you so much for reply, I search it up and discovered that physicle data which include throttle and braking data is sending via different method like udp packet, and I can't decode raw data so I giving up for now, thank you so much for making this amazing tool and the information.

**Comment by EmperorCookie** [comment]
If this information is available in other ways, it may be added in the future, but not for now.
