### ISSUE TITLE
AccClient exits immediately if ACC is not running yet

### ISSUE THREAD

**Issue by ptoews** [EmperorCookie/accapi#6]
When `AccClient.start()` is executed before the game is running, a `ConnectionResetError` is thrown and this break is executed:

https://github.com/EmperorCookie/accapi/blob/f93040b4b8ae30f569efadfe4e29ce9761155a9d/src/accapi/client.py#L399-L406

This causes a full shutdown of client and reader.

It might be preferrable to keep retrying, similar to how the timeout is handled. Otherwise the user of the API has to keep retrying executing `start()` without even being notified about an error, or has to implement some mechanism to detect if the game is already running.

**Comment by EmperorCookie** [comment]
That could potentially be a feature request.

I feel like this kind of behavior would be better handled by the application being built rather than the library. Opinions?

**Comment by EmperorCookie** [comment]
I forgot to address the issue you raised about the application having to detect if the game is running. That is solved simply by either registering a callback for `onConnectionStateChange` and checking for "lost" or checking `client.connectionState` in a wait loop.

**Comment by ptoews** [comment]
Yes I think you're right, the application should have full control over this. At first I thought that break could be replaced with an exception being thrown to at least signal that the game isn't running, but since that runs in an own thread that doesn't make sense.

Checking the connection state might indeed be a proper solution, however there is still the option to provide a convenience flag to `AccClient` which could enable automatic retrying of establishing a connection to the game API.

**Comment by EmperorCookie** [comment]
Having more options is not always the best. I could see a `timeout` kwarg be added to the `start` method, but it would require weird behavior in order to account for all use cases.

**Comment by EmperorCookie** [comment]
I will close this for now, the application can handle all of this fairly easily with the callbacks and the connection status.
